### ISSUE TITLE
想问下私钥计算过程的获取方式?

### ISSUE THREAD

**Issue by 0CBH0** [ash255/wibu#1]
想问下您这里的私钥计算过程是通过逆向CodeMeter获得的吗?

**Comment by ash255** [comment]
CodeMeter Runtime For Linux中的CodeMeterLin包含了验证流程

**Comment by 0CBH0** [comment]
所以cmu会调用CodeMeterLin？
win版里没有CodeMeterLin 但有cmu32 我如果想去分析win的验证过程 是不是从cmu32入手比较好？

**Comment by ash255** [comment]
CodeMeter Runtime For Win中的CodeMeter.exe对应CodeMeterLin，应该从CodeMeter.exe入手，cmu只是处理用户输入并将用户输入转换为请求，然后提交到CodeMeter中。

**Comment by 0CBH0** [comment]
了解了 我去尝试一下 谢谢您！
